EXPERIMENT: "OSNet_SGD"

TASK: "cifar10"
MANAGER: "imagenet"
ENGINE: "imagenet"
TRAINER: "imagenet"
NUM_WORKERS: 8

MODEL:
  GPU: [1]
  NAME: 'osnet'

INPUT:
  RESIZE: (32, 32)
  TRAIN_BS: 256
  TEST_BS: 256
  MEAN: [0.4914, 0.4822, 0.4465]
  STD: [0.2470, 0.2435, 0.2616]
  RAND_AUG_N: 2
  RAND_AUG_M: 10

DB:
  NUM_CLASSES: 10 #D:702, M:751 MSMT:2012(merge)
  DATA: "cifar10"
  DATASET: "cifar10"
  LOADER: "cifar10"
  USE_TRAIN: True
  USE_TEST: True
  PATH: "/media/allen/mass/DB/"

TRAIN_TRANSFORM: "resize hflip randaug tensorize normalize"
TEST_TRANSFORM: "resize tensorize normalize"

SOLVER:
  OPTIMIZER_NAME: "SGD"
  START_EPOCH: 0
  MAX_EPOCHS: 400
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  EVALUATE_FREQ: 1

  LR_POLICY: "plateau"
  MIN_LR: 1e-6
  # WARMUP: True
  GAMMA: 0.1
  # WARMUP_FACTOR: 0.01
  # WARMUP_SIZE: 10.0
  PLATEAU_SIZE: 10.0

# RESUME: ["main", "/media/allen/mass/deep-learning-works/result_2019-06-28_18:09:28/weights/model_main_277_92.4000.pth", "fc", "/media/allen/mass/deep-learning-works/result_2019-06-28_18:09:28/weights/model_fc_277_92.4000.pth"]
# EVALUATE: ["main", "/media/allen/mass/deep-learning-works/result_2019-06-28_18:09:28/weights/model_main_277_92.4000.pth", "fc", "/media/allen/mass/deep-learning-works/result_2019-06-28_18:09:28/weights/model_fc_277_92.4000.pth"]

