EXPERIMENT: "OSNet_ce_SGD_plateau_lr0.05_ImageNet"

TASK: "imagenet"

MODEL:
  NUM_GPUS: 2
  NUM_CLASSES: 1000
  NAME: "osnet"
  PRETRAIN: ""

INPUT:
  IMAGE_PAD: 0
  IMAGE_SIZE: (256, 256)
  IMAGE_CROP_SIZE: (224, 224)
  TRAIN_BS: 256
  TEST_BS: 256
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  
DATALOADER:
  NUM_WORKERS: 30

DATASET:
  NAME: "imagenet"
  TRAIN_PATH: "/home/allen.jc.lin/imagenet"

TRANSFORM:
  HFLIP: True
  RANDOMCROP: True
  NORMALIZE: True
  RESIZE: True 
  SINGLE_CROP: True

SOLVER:
  OPTIMIZER_NAME: "SGD"
  START_EPOCH: 0
  MAX_EPOCHS: 1000
  BASE_LR: 0.05
  BIAS_LR_FACTOR: 1.0
  # CENTER_LOSS_LR: 0.5
  # CENTER_LOSS_WEIGHT: 0.0005
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  EVALUATE_FREQ: 1

  LR_POLICY: "plateau"
  WARMUP: False
  GAMMA: 0.1
  # WARMUP_FACTOR: 0.01
  WARMUP_SIZE: 1.0
  PLATEAU_SIZE: 5.0
  WARMRESTART_MULTIPLIER: 2
  WARMRESTART_PERIOD: 5

# EVALUATE: "/home/allen.jc.lin/osnet_x1_0_imagenet.pth"
