# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "OSNet_merge_cels-triplet-center_AdamW-lr-0.00035-warmup-plateau_imagenet"
RESUME: "/media/allen/mass/osnet_x1_0_imagenet.pth"
EVALUATE: True
SAVE: True
IO: True
SEED: 42
ENGINE: "trick_reid"
GRAPH: "trick_reid"
TRAINER: "trick_reid"
NUM_WORKERS: 1
EVALUATE_FREQ: 5
MODEL:
  GPU: []
  BACKBONE: "osnet_deep_reid"
  STRIDE: 32
  FEATSIZE: 512
INPUT:
  PAD: 10
  SIZE: (256, 128)
  TRAIN_BS: 16
  TEST_BS: 2
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/path/to/data"
  DATA: "msmt cuhk01 cuhk02 cuhk03 duke market"
  DATA_FORMAT: "reid"
  LOADER: "reid"
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "Resize RandCrop RandomHFlip AugMix Tensorize Normalize"
  TEST_TRANSFORM: "Resize Tensorize Normalize"
SOLVER:
  OPTIMIZER: "AdamW"
  START_EPOCH: 1
  MAX_EPOCHS: 400
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  CUSTOM: [["bn", "wd", 0.0]]
  LR_POLICY: "plateau"
  MIN_LR: 1e-6
  WARMUP: True
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_SIZE: 10.0
  PLATEAU_SIZE: 10.0
REID:
  SIZE_PERSON: 4