# [modelname]_[task]_[loss]_[opt]_[lr]_[trick]_[pretrain]
EXPERIMENT: "SPOS-search-shufflenetv2-tinyimagenet"
RESUME: "/home/agent/deep-learning-works/result/tinyimagenet/SPOS-supernet-shufflenetv2_tinyimagenet_augmix-ce_SGDW-cosine-0.01-noRestart-warmup_scratch/005-2020-03-18_03-49/weights/model_119_0.0000.pth"
SEED: 42
GRAPH: "shufflenetv2_spos_classification"
NUM_WORKERS: 32

MODEL:
  GPU: [0, 1]
  BACKBONE: ''
  FEATSIZE: 464

INPUT:
  SIZE: (64, 64)
  TRAIN_BS: 64
  TEST_BS: 512
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]  

DB:
  PATH: "/home/agent/deep-learning-works/data"
  NUM_CLASSES: 200
  DATA: "tinyimagenet"
  DATA_FORMAT: "imagenet"
  LOADER: "classification"
  USE_TEST: True
  TEST_TRANSFORM: "Tensorize Normalize"

