# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "Shufflenetv2_hrnet-cifar10-ce-SGDW_nesterov_lr_0.1_cosine-scratch"
# EVALUATE: True
# RESUME: "/home/agent/osnet_x1_0_imagenet.pth"
APEX: True
SAVE: True
IO: True
SEED: 42
ENGINE: "classification"
GRAPH: "simple_classifier"
TRAINER: "imagenet"
NUM_WORKERS: 3
EVALUATE_FREQ: 10
DISTRIBUTED: True
MODEL:
  GPU: [0,1,2,3]
  BACKBONE: "hrnet_cifar"
  FEATSIZE: 1024
INPUT:
  PAD: 4
  SIZE: (32, 32)
  TRAIN_BS: 128
  TEST_BS: 256
  MEAN: [0.4914, 0.4822, 0.4465]
  STD: [0.2470, 0.2435, 0.2616]  
DB:
  PATH: "/home/agent"
  DATA: "cifar10"
  DATA_FORMAT: "cifar10"
  LOADER: "classification"
  NUM_CLASSES: 10
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "RandCrop RandomHFlip Tensorize Normalize"
  TEST_TRANSFORM: "Tensorize Normalize"
SOLVER:
  OPTIMIZER: "SGDW"
  NESTEROV: True
  MOMENTUM: 0.9
  START_EPOCH: 1
  BASE_LR: 0.05
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  LR_POLICY: "cosine-1-1-100-1"
