# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "Shufflenetv2_hrnet-imagenet-ce-SGDW_nesterov_lr_0.1_cosine-scratch"
# EVALUATE: True
# RESUME: "/home/agent/osnet_x1_0_imagenet.pth"
APEX: False
SAVE: True
IO: True
SEED: 42
ENGINE: "classification"
GRAPH: "simple_classifier"
TRAINER: "imagenet"
NUM_WORKERS: 3
EVALUATE_FREQ: 3
DISTRIBUTED: True
MODEL:
  GPU: [0,1,2]
  BACKBONE: "hrnet_cls"
  FEATSIZE: 2048
INPUT:
  PAD: 10
  SIZE: (224,224)
  TRAIN_BS: 64
  TEST_BS: 256
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/home/agent"
  DATA: "imagenet"
  DATA_FORMAT: "imagenet"
  LOADER: "classification"
  NUM_CLASSES: 1000
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "Resize RandCrop RandomHFlip RandomColorJitter-0.8-0.15-0.15-0.1-0.1 RandomRotate-0.33 RandomGrayScale-0.1 Tensorize Normalize"
  TEST_TRANSFORM: "Resize Tensorize Normalize"
SOLVER:
  OPTIMIZER: "SGDW"
  NESTEROV: True
  MOMENTUM: 0.9
  START_EPOCH: 1
  BASE_LR: 0.1
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  LR_POLICY: "cosine-1-1-90-1"
