EXPERIMENT: "ShuffleNetv2+-MobileNetv3_emotion_cels_SGDW_cosine-lr-0.1_scratch"
# [modelname]_[task]_[loss]_[opt]_[lr]_[trick]_[pretrain]

SAVE: True
IO: True
TRAINER: "imagenet"
ENGINE: "classification"
GRAPH: "shufflenetv2plus_classification"
EVALUATE_FREQ: 1
# EVALUATE: True
NUM_WORKERS: 16
MODEL:
  GPU: [1]
  BACKBONE: "shufflenetv2+"

INPUT:
  SIZE: (112, 112)
  TRAIN_BS: 512
  TEST_BS: 512
  # MEAN: [0.485, 0.456, 0.406]
  # STD: [0.229, 0.224, 0.225]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]

DB:
  PATH: "/home/agent/deep-learning-works/data"
  NUM_CLASSES: 7
  DATA: "emotion"
  DATA_FORMAT: "imagenet"
  TARGET_FORMAT: "imagenet" 
  LOADER: "classification"
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "AugMix Tensorize Normalize"
  TEST_TRANSFORM: "Tensorize Normalize"


SOLVER:
  OPTIMIZER: "Adam"
  START_EPOCH: 1
  MAX_EPOCHS: 400
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0

  LR_POLICY: "cosine"
  T_0: 400
  # MIN_LR: 1e-6
  # WARMUP: True
  # GAMMA: 0.1
  # WARMUP_FACTOR: 0.01
  # WARMUP_SIZE: 10.0
  # PLATEAU_SIZE: 10.0

# RESUME: '/media/allen/mass/deep-learning-works/caffe_models/Hourglass-squeeze_coco_focal_regl1_Freeze_Adam_lr_0.0001_plateau_10_COCO_0.2981.pth'
