EXPERIMENT: "Hourglass-Squeeze_deepfashion_focal_regl1_regwl1_Adam_lr_0.0005_plateau_10_coco"
# [modelname]_[task]_[loss]_[opt]_[lr]_[trick]_[pretrain]

TASK: "keypoint"
MANAGER: "center_kp"
ENGINE: "center_kp"
TRAINER: "center_kp"
ORACLE: False
NUM_WORKERS: 8
MODEL:
  GPU: [1]
  NAME: "light_hourglass"
  NORM: 'BN'

INPUT:
  RESIZE: (512,512)
  TRAIN_BS: 1
  TEST_BS: 1

COCO:
  TARGET: ('original', -1)

DB:
  NUM_CLASSES: 13 #D:702, M:751 MSMT:2012(merge)
  NUM_KEYPOINTS: 294
  DATA: "deepfashion"
  DATASET: "coco_keypoint"
  LOADER: "coco"
  USE_TRAIN: False
  USE_TEST: True
  PATH: "/media/allen/mass/DB/"

SOLVER:
  OPTIMIZER: "Adam"
  START_EPOCH: 0
  MAX_EPOCHS: 400
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  EVALUATE_FREQ: 5

  LR_POLICY: "plateau"
  MIN_LR: 1e-6
  # WARMUP: True
  GAMMA: 0.1
  # WARMUP_FACTOR: 0.01
  # WARMUP_SIZE: 10.0
  PLATEAU_SIZE: 10.0

EVALUATE: '/media/allen/mass/deep-learning-works/caffe_models/Hourglass-squeeze_coco_focal_regl1_Freeze_Adam_lr_0.0001_plateau_10_COCO_0.2981.pth'
