# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "OSNet_IAP-msmt-amsoftmax-AdamW_amsgrad_lr_0.0015_freeze_step-scratch"
EVALUATE: True
RESUME: "/media/allen/mass/deep-learning-works/result/msmt market/OSNet_IAP-msmt-amsoftmax-AdamW_amsgrad_lr_0.0015_freeze_step-scratch/000-2020-03-30_23-19/weights/model_055_0.6129.pth"
# "/media/allen/mass/osnet_x1_0_imagenet.pth"
SAVE: True
IO: True
SEED: 42
ENGINE: "iap_reid"
GRAPH: "iap_reid"
TRAINER: "iap_reid"
NUM_WORKERS: 1
EVALUATE_FREQ: 5
MODEL:
  GPU: [1]
  BACKBONE: "osnet_deep_reid_iap"
  FEATSIZE: 512
INPUT:
  PAD: 10
  SIZE: (128, 256)
  TRAIN_BS: 64
  TEST_BS: 256
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/media/allen/mass/DB"
  DATA: "msmt duke"
  DATA_FORMAT: "reid"
  LOADER: "reid"
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "RandomGrid-0.15 RandomPadding-0.25 RandomFigures-0.5 Resize RandomHFlip RandomColorJitter-0.8-0.15-0.15-0.1-0.1 RandomRotate-0.33 RandomGrayScale-0.1 Tensorize RandomErasing-0.5 Normalize"
  TEST_TRANSFORM: "Resize Tensorize Normalize"
SOLVER:
  OPTIMIZER: "AdamW"
  AMSGRAD: True
  START_EPOCH: 1
  BASE_LR: 0.0015
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  LR_POLICY: "step-40-0-0.1 step-10-1-0.1 step-15-2-0.1"
  MODEL_FREEZE_PEROID: 5
REID:
  SIZE_PERSON: 4
  MSMT_ALL: True