# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "OSNet_IAP-msmt_duke_cuhk123-amsoftmax-AdamW_amsgrad_lr_0.0005_freeze_step-imagenet"
# EVALUATE: True
RESUME: "/home/agent/osnet_x1_0_imagenet.pth"
APEX: True
SAVE: True
IO: True
SEED: 42
ENGINE: "iap_reid"
GRAPH: "iap_reid"
TRAINER: "iap_reid"
NUM_WORKERS: 3
EVALUATE_FREQ: 1
DISTRIBUTED: True
MODEL:
  GPU: [0,1,2]
  BACKBONE: "osnet_deep_reid_iap"
  FEATSIZE: 512
INPUT:
  PAD: 10
  SIZE: (128, 256)
  TRAIN_BS: 64
  TEST_BS: 256
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/home/agent/person_reid"
  DATA: "msmt duke cuhk01 cuhk02 cuhk03"
  DATA_FORMAT: "reid"
  LOADER: "reid"
  USE_TRAIN: True
  USE_TEST: True
  TRAIN_TRANSFORM: "RandomGrid-0.15 RandomPadding-0.25 RandomFigures-0.5 Resize RandomHFlip RandomColorJitter-0.8-0.15-0.15-0.1-0.1 RandomRotate-0.33 RandomGrayScale-0.1 Tensorize RandomErasing-0.5 Normalize"
  TEST_TRANSFORM: "Resize Tensorize Normalize"
SOLVER:
  OPTIMIZER: "AdamW"
  AMSGRAD: True
  START_EPOCH: 1
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS_FACTOR: 1.0
  LR_POLICY: "step-40-0-0.1 step-10-1-0.1 step-15-2-0.1"
  MODEL_FREEZE_PEROID: 5
REID:
  SIZE_PERSON: 4
  MSMT_ALL: True
