# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "Shufflenetv2Plus_csp-cityperson-person-focal_l1-AdamW_lr_0.0015_cosine_imagenet"
PRETRAIN: True
RESUME: "/home/agent/deep-learning-works/external/ShuffleNetV2+.Medium.pth.tar"
APEX: True
SAVE: True
IO: True
# EVALUATE: True
ENGINE: "shufflenetv2_object_detection"
GRAPH: "shufflenetv2_csp"
TRAINER: "jde"
NUM_WORKERS: 2
# ORACLE: True
EVALUATE_FREQ: 5
DISTRIBUTED: True
MODEL:
  GPU: [0,1,2,3]
  BACKBONE: "shufflenetv2+_csp"
  STRIDES: [4]
  FEATSIZE: 256
  MAX_STRIDE: 32
INPUT:
  SIZE: (512,512)
  TRAIN_BS: 16
  TEST_BS: 1
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/home/agent/person_jde"
  DATA: "cityperson"
  DATA_FORMAT: "coco"
  LOADER: "coco"
  NUM_CLASSES: 1
  USE_TRAIN: True
  USE_TEST: True
  TARGET_FORMAT: "centernet" 
  TRAIN_TRANSFORM: "RandScale-0.4-1.5 RandomHFlip RandomColorJitter-0.8-0.15-0.15-0.1-0.1 Tensorize Normalize"
  TEST_TRANSFORM: "ResizeFit Tensorize Normalize"
SOLVER:
  OPTIMIZER: "AdamW"
  START_EPOCH: 1
  BASE_LR: 0.0015
  LR_POLICY: "cosine-3-1.0-10-2"
COCO:
  TARGET: 'person'

