# [modelname]_[task]_[loss]_[opt]_[pretrain]
EXPERIMENT: "Shufflenetv2_hrnet_scopehead-crowdhuman_cuhksysu_ethz_prw_caltech_cityperson-person-focal_l1_ciou-AdamW_lr_0.0015_cosine_imagenet"
PRETRAIN: True
RESUME: "/media/acer/5f45949f-0fc7-4475-965b-e61989afcc10/Downloads/result-200603/crowdhuman cuhksysu ethz prw caltech cityperson crowdhuman/Shufflenetv2_hrnet_scopehead-crowdhuman_cuhksysu_ethz_prw_caltech_cityperson-person-focal_l1_ciou-AdamW_lr_0.0015_cosine_imagenet/001-2020-06-02_06-30/weights/model_030_0.2469.pth"
APEX: True
SAVE: True
IO: True
# EVALUATE: True
ENGINE: "shufflenetv2_scopehead_object_detection"
GRAPH: "shufflenetv2_scopehead_object_detection"
TRAINER: "jde"
NUM_WORKERS: 2
# ORACLE: True
EVALUATE_FREQ: 5
DISTRIBUTED: True
MODEL:
  GPU: [0,1,2,3]
  BACKBONE: "hrnet"
  STRIDES: [4]
  FEATSIZE: 256
INPUT:
  SIZE: (512,512)
  TRAIN_BS: 16
  TEST_BS: 1
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DB:
  PATH: "/home/agent/person_jde"
  DATA: "crowdhuman cuhksysu ethz prw caltech cityperson crowdhuman"
  DATA_FORMAT: "coco"
  LOADER: "coco"
  NUM_CLASSES: 1
  USE_TRAIN: True
  USE_TEST: True
  TARGET_FORMAT: "scopehead" 
  TRAIN_TRANSFORM: "RandScale RandomHFlip RandomColorJitter-0.8-0.15-0.15-0.1-0.1 Tensorize Normalize"
  TEST_TRANSFORM: "ResizeKeepAspectRatio Tensorize Normalize"
SOLVER:
  OPTIMIZER: "AdamW"
  START_EPOCH: 1
  BASE_LR: 0.0015
  LR_POLICY: "warm-10 cosine-1-1-120-1"
COCO:
  TARGET: 'person'

